services:
  moodle:
    build:
      context: ./moodle
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME:-moodle-jupyter-platform}_moodle
    env_file:
      - path: .env
        required: true
    environment:
      TZ: ${TZ:-Asia/Ho_Chi_Minh}
      MOODLE_WWWROOT: ${MOODLE_WWWROOT:-http://localhost:18080}
      POSTGRES_HOST: ${POSTGRES_HOST:-infra-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${MOODLE_DB_NAME:-moodle}
      POSTGRES_USER: ${MOODLE_DB_USER:-moodle_user}
      POSTGRES_PASSWORD: ${MOODLE_DB_PASSWORD:-moodle_password}
      MOODLE_ADMIN_USER: ${MOODLE_ADMIN_USER:-admin}
      MOODLE_ADMIN_PASSWORD: ${MOODLE_ADMIN_PASSWORD:-admin123}
      MOODLE_ADMIN_EMAIL: ${MOODLE_ADMIN_EMAIL:-admin@example.com}
    ports:
      - "${MOODLE_HOST_PORT:-18080}:80"
    volumes:
      - ${DATA_ROOT}/moodledata:/var/moodledata
    networks:
      - infra-data-net

  jupyterhub:
    build:
      context: ./jupyterhub
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME:-moodle-jupyter-platform}_jupyterhub
    env_file:
      - path: .env
        required: true
      - path: ./generated/lti.env
        required: false
    environment:
      TZ: ${TZ:-Asia/Ho_Chi_Minh}
      MOODLE_WWWROOT: ${MOODLE_WWWROOT:-http://localhost:18080}
      JUPYTERHUB_URL: ${JUPYTERHUB_URL:-http://localhost:18000}
      JUPYTERHUB_DB_URL: ${JUPYTERHUB_DB_URL:-postgresql://jupyterhub_user:jupyterhub_password@infra-postgres:5432/jupyterhub}
      LTI_USERNAME_KEY: ${LTI_USERNAME_KEY:-email}
    depends_on:
      moodle:
        condition: service_started
    ports:
      - "${JUPYTERHUB_HOST_PORT:-18000}:8000"
    volumes:
      - ${DATA_ROOT}/jupyter_users:/home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - infra-data-net

  jupyter-assignment-service:
    build:
      context: ./jupyter-assignment-service
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME:-moodle-jupyter-platform}_jupyter-assignment-service
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_ROOT}/nbgrader/courses:/srv/nbgrader/courses
      - ${DATA_ROOT}/nbgrader/templates:/srv/nbgrader/templates
      - ${DATA_ROOT}/nbgrader/exchange:/srv/nbgrader/exchange
    environment:
      - JUPYTERHUB_API_URL=http://jupyterhub:8000/hub/api
      - JUPYTERHUB_API_TOKEN=super-secret-token
    networks:
      - infra-data-net
    depends_on:
      - jupyterhub

  jupyter-singleuser:
    build:
      context: ./jupyter-singleuser
      dockerfile: Dockerfile
    image: moodle-jupyter-singleuser:latest
    profiles:
      - jupyterhub-spawnable

networks:
  infra-data-net:
    name: infra-data-net
    external: true

