#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_ROOT"

# Load biến môi trường
if [ -f .env ]; then
    set -a
    . ./.env
    set +a
fi

POSTGRES_ADMIN_USER=${POSTGRES_ADMIN_USER:-postgres_user}
POSTGRES_DB=${POSTGRES_DB:-postgres_app_db}

# 1. Đọc cấu hình Moodle
MOODLE_DB_NAME=${MOODLE_DB_NAME:-moodle}
MOODLE_DB_USER=${MOODLE_DB_USER:-moodle_user}
MOODLE_DB_PASSWORD=${MOODLE_DB_PASSWORD:-moodle_password}

# 2. Đọc cấu hình JupyterHub
JUPYTERHUB_DB_NAME=${JUPYTERHUB_DB_NAME:-jupyterhub}
JUPYTERHUB_DB_USER=${JUPYTERHUB_DB_USER:-jupyterhub_user}
JUPYTERHUB_DB_PASSWORD=${JUPYTERHUB_DB_PASSWORD:-jupyterhub_password}

# 3. Đọc cấu hình Assignment Service
ASSIGNMENT_DB_NAME=${ASSIGNMENT_DB_NAME:-assignment_service}
ASSIGNMENT_DB_USER=${ASSIGNMENT_DB_USER:-assignment_user}
ASSIGNMENT_DB_PASSWORD=${ASSIGNMENT_DB_PASSWORD:-moodle_jupyter_assign_pass}

echo "=== Đang cấu hình và đảm bảo các database/users tồn tại trên infra-postgres ==="

docker exec -i infra-postgres psql -U "$POSTGRES_ADMIN_USER" -d "$POSTGRES_DB" <<SQL >/dev/null
-- 1. Thiết lập cho Moodle
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '$MOODLE_DB_USER') THEN
    CREATE ROLE "$MOODLE_DB_USER" LOGIN PASSWORD '$MOODLE_DB_PASSWORD';
  ELSE
    ALTER ROLE "$MOODLE_DB_USER" WITH LOGIN PASSWORD '$MOODLE_DB_PASSWORD';
  END IF;
END
\$\$;

SELECT 'CREATE DATABASE "$MOODLE_DB_NAME" OWNER "$MOODLE_DB_USER"'
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = '$MOODLE_DB_NAME')\gexec

ALTER DATABASE "$MOODLE_DB_NAME" OWNER TO "$MOODLE_DB_USER";
GRANT ALL PRIVILEGES ON DATABASE "$MOODLE_DB_NAME" TO "$MOODLE_DB_USER";

-- 2. Thiết lập cho JupyterHub
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '$JUPYTERHUB_DB_USER') THEN
    CREATE ROLE "$JUPYTERHUB_DB_USER" LOGIN PASSWORD '$JUPYTERHUB_DB_PASSWORD';
  ELSE
    ALTER ROLE "$JUPYTERHUB_DB_USER" WITH LOGIN PASSWORD '$JUPYTERHUB_DB_PASSWORD';
  END IF;
END
\$\$;

SELECT 'CREATE DATABASE "$JUPYTERHUB_DB_NAME" OWNER "$JUPYTERHUB_DB_USER"'
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = '$JUPYTERHUB_DB_NAME')\gexec

ALTER DATABASE "$JUPYTERHUB_DB_NAME" OWNER TO "$JUPYTERHUB_DB_USER";
GRANT ALL PRIVILEGES ON DATABASE "$JUPYTERHUB_DB_NAME" TO "$JUPYTERHUB_DB_USER";

-- 3. Thiết lập cho Assignment Service
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '$ASSIGNMENT_DB_USER') THEN
    CREATE ROLE "$ASSIGNMENT_DB_USER" LOGIN PASSWORD '$ASSIGNMENT_DB_PASSWORD';
  ELSE
    ALTER ROLE "$ASSIGNMENT_DB_USER" WITH LOGIN PASSWORD '$ASSIGNMENT_DB_PASSWORD';
  END IF;
END
\$\$;

SELECT 'CREATE DATABASE "$ASSIGNMENT_DB_NAME" OWNER "$ASSIGNMENT_DB_USER"'
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = '$ASSIGNMENT_DB_NAME')\gexec

ALTER DATABASE "$ASSIGNMENT_DB_NAME" OWNER TO "$ASSIGNMENT_DB_USER";
GRANT ALL PRIVILEGES ON DATABASE "$ASSIGNMENT_DB_NAME" TO "$ASSIGNMENT_DB_USER";
SQL

echo "=== Đã hoàn tất cấu hình database. ==="
echo "   - Database '$MOODLE_DB_NAME' cho user '$MOODLE_DB_USER': OK"
echo "   - Database '$JUPYTERHUB_DB_NAME' cho user '$JUPYTERHUB_DB_USER': OK"
echo "   - Database '$ASSIGNMENT_DB_NAME' cho user '$ASSIGNMENT_DB_USER': OK"
